trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Contruyendo Aplicación
  jobs:
  - job: job01
    displayName: Compilando
    steps:
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'manueltello2026'
      displayName: Autenticando Artifacts
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'sc_sonarqube_prd'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'labmaven02'
        cliProjectName: 'labmaven02'
        cliSources: '.'
      displayName: Preparar Configuracion de Sonar 
    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
      displayName: Analizando Codigo
    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'
      displayName: Publicando Resultado  
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      displayName: Contruyendo Artefacto
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'deploy'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      displayName: Publicando Artefacto en Artifacts
    - task: CopyFiles@2
      inputs:
        Contents: 'target/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
      displayName: Copiando Artefacto
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'artifact'
        publishLocation: 'Container'
      displayName: Publicando Artefacto